### ISSUE TITLE
Index data with WKT but no EPSG code

### ISSUE THREAD

**Issue by clausmichele** [opendatacube/datacube-core#1014]
I have a dataset with WKT but no EPSG code. It has a custom projection describable by PROJ and readable by GDAL. How do I index it? I attach here the datacube product definition and dataset yaml. The error I get when I try to load the data is: `ValueError: Product has no default CRS. Must specify 'output_crs' and 'resolution'` but I can't specify the output_crs since I don't have an EPSG code. Am I missing something?

* Which ``datacube --version`` are you using?
1.8

[MOD16_mosaic_product.txt](https://github.com/opendatacube/datacube-core/files/5188494/MOD16_mosaic_product.txt)
[2019_dataset.txt](https://github.com/opendatacube/datacube-core/files/5188495/2019_dataset.txt)

**Comment by tushar10sh** [comment]
If your **product** (MOD16_mosaic in your case) has common projection parameter for all the datasets which you are going to index under this product name, then you can mention this projection wkt as following in your product definition document. Dataset document will remain as it is. Hope this helps.

```
name: MOD16_mosaic
description: MOD16_mosaic
metadata_type: eo

metadata:
    platform: {code: MODIS}
    instrument: {name: MODIS}
    product_type: MOD16_mosaic
    format: {name: GeoTIFF}

storage:
  driver: GeoTIFF
  crs: PROJCS["unnamed",GEOGCS["Unknown datum based upon the custom spheroid",DATUM["Not_specified_based_on_custom_spheroid",SPHEROID["Custom spheroid",6371007.181,0]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Sinusoidal"],PARAMETER["longitude_of_center",0],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]]]
  resolution: 
   x: 463.312716527742680
   y: -463.312716527742680
  
measurements:
    - name: '0'
      dtype: uint16
      nodata: 0
      units: '1'

```
