### ISSUE TITLE
Values from netcdf file different after querying with odc

### ISSUE THREAD

**Issue by jankovicgd** [opendatacube/datacube-core#1036]
Hey all, I am having a bit of a weird issue with some data provided with opendatacube.

### Expected behaviour
The expectation is that the values loaded with `Datacube.load()` are the same as when i use `xarray.open` or inspect with qgis/panoply... I am providing a single netcdf file.

### Actual behaviour

When i use the `xarray.DataArray.sel` method i get the two different arrays in the same spatiotemporal area:

* `array([-79., -78., -75., -73., -70.], dtype=float32)` - This is returned with opendatacube - datacube.Datacube.load and then extracting the array and using `.sel(latitude=..., longitude=..., method='nearest')`
* `array([-0.0058, -0.0056, -0.0053, -0.005 , -0.0047], dtype=float32)` - This is the actual data that i can inspect with panoply, qgis and using `xarray.open_dataset()` extracting the array and using `.sel(latitude=..., longitude=..., method='nearest')`

### Steps to reproduce the behaviour

using xarray:
```python
import xarray
ds = xarray.open_dataset('/home/nikola/Data/Projects/SULAMOSA/new/SD066_sbas.nc', decode_times=False) #decode_times required not loading otherwise
lat_lon = [47.41391731136826, 9.645652770996096]
ds.deformation_up_down.sel(latitude=lat_lon[0], longitude=lat_lon[1], method='nearest').sel(date=slice(1035, 1064))
```
using odc:
```python
# values picked up from function call
with datacube.Datacube(env=environment) as dc:
            data = dc.load(
                product=product,
                time=(start_date, end_date),
                measurements=[band],
                lat=(bounds[0][0], bounds[1][0]),
                lon=(bounds[0][1], bounds[1][1]),
            )
            data_arr = data.get(band)

            selection = data_arr.sel(
                latitude=click_lat_lng[0],
                longitude=click_lat_lng[1],
                method="nearest",
            )
```

Product:
```yaml
name: DEF_Mixed
description: Todo
metadata_type: eo

storage:
  crs: EPSG:4326
  resolution:
    latitude: 0.00071335
    longitude: 0.00107861

metadata:
  format: { name: NetCDF }
  instrument: { name: Mixed }
  platform: { code: Mixed }
  product_type: J_DEF_MIX

measurements:
  - name: deformation_up_down
    aliases: [band_1]
    units: "m"
    dtype: float32
    nodata: -32768
```

Another bit of information is this warning:
```
Broken/missing geospatial data was found in file:
"NetCDF:"/home/nikola/Data/Projects/SULAMOSA/new/SD066_sbas_test.nc":deformation_up_down"
Will use approximate metadata for backwards compatibility reasons (#673).
This behaviour is deprecated. Future versions will raise an error.
```

I assume this is due to the CRS definition missing in the file (which should be added), and I am not sure it relates to the main issue.

### Environment information

* Which ``datacube --version`` are you using? 1.8.3
* What datacube deployment/enviornment are you running against? Local setup with pip and database running in docker (database docker setup currently uses datacube-ows because i am also trying out stuff from there)

**Comment by Kirill888** [comment]
it's not georegistered and because of poor choices we load data anyway with reprojection and hence everything is broken.
See issue #673 referenced in the warning message.

**Comment by jankovicgd** [comment]
Thanks for the help, I'll reply & probably close once I get the updated data.

**Comment by jankovicgd** [comment]
So, I updated the file and still I seem to get wrong values. The variables are linked to this variable in the netCDF:
```double latitude_longitude;
  :crs_wkt = "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]";
  :_FillValue = NaN; // double
  :grid_mapping_name = "latitude_longitude";
  :spatial_ref = "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]";
```

Here is a graph computed with the xarray.Dataset.sel(): [https://i.imgur.com/T3u5lis.png](https://i.imgur.com/T3u5lis.png)
Here is a histogram for the file in qgis: [https://i.imgur.com/sfdXIMS.png](https://i.imgur.com/sfdXIMS.png)

any idea?

**Comment by Kirill888** [comment]
@jankovicgd I don't have enough information to debug your issue. Please share the file.

**Comment by jankovicgd** [comment]
Here you go: [https://mega.nz/file/6dIBwSgZ#au5JIIN1dox9pXzszn1T7siczgf6UMq-SQ0qPN9sCNE](https://mega.nz/file/6dIBwSgZ#au5JIIN1dox9pXzszn1T7siczgf6UMq-SQ0qPN9sCNE)

**Comment by jankovicgd** [comment]
Product yml:
```yaml
name: DEF_Mixed
description: Todo
metadata_type: eo

storage:
  crs: GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
  resolution:
    latitude: 0.00071335
    longitude: 0.00107861

metadata:
  format: { name: NetCDF }
  instrument: { name: Mixed }
  platform: { code: Mixed }
  product_type: J_DEF_MIX

measurements:
  - name: deformation_up_down
    aliases: [band_1]
    units: "m"
    dtype: float32
    nodata: -32768
```
There are multiple dataset ymls with different dates:
```yaml
extent:
  center_dt: '2017-03-16T00:00:00'
  coord:
    ll:
      lat: 46.79846954345703
      lon: 9.31406307220459
    lr:
      lat: 46.79846954345703
      lon: 10.462111473083496
    ul:
      lat: 47.643978118896484
      lon: 9.31406307220459
    ur:
      lat: 47.643978118896484
      lon: 10.462111473083496
  from_dt: '2017-03-16T00:00:00'
  to_dt: '2017-03-16T00:00:00'
format:
  name: NetCDF
grid_spatial:
  projection:
    geo_ref_points:
      ll:
        x: 9.31406307220459
        y: 46.79846954345703
      lr:
        x: 10.462111473083496
        y: 46.79846954345703
      ul:
        x: 9.31406307220459
        y: 47.643978118896484
      ur:
        x: 10.462111473083496
        y: 47.643978118896484
    spatial_reference: GEOGCS["WGS84",DATUM["WGS_1984",SPHEROID["WGS84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
id: f21a6e53-2bde-463f-b16f-c3f3fcbd6314
image:
  bands:
    deformation_up_down:
      band: 3
      layer: deformation_up_down
      path: /home/nikola/Data/Projects/SULAMOSA/new/SD_066_sbas_final.nc
instrument:
  name: Mixed
lineage:
  source_datasets: {}
name: J_DEF_MIX_20170316000000
platform:
  code: Mixed
product_type: J_DEF_MIX
```
