### ISSUE TITLE
Description of 2D coordinates

### ISSUE THREAD

**Issue by sophieherrmann** [opendatacube/datacube-core#1083]
Hi everyone!

I want to index netCDF data into ODC. The problematic dataset uses 2-dimensional coordinates and I'm not sure how to describe those within proudct and dataset yml files.

### Expected behaviour

The expected behaviour is that opening the dataset with `xarray.open_dataset('file.nc')` gives the same result as loading it with `dc.load(product=product)`

### Actual behaviour

Opening the original .nc file with `xarray.open_dataset('file.nc')` gives:

```
<xarray.Dataset>
Dimensions:         (X: 689, Y: 309, time: 1, time_1day: 24)
Coordinates:
  * time            (time) datetime64[ns] 2019-01-01T23:00:00
    Longitude       (Y, X) float32 ...
    Latitude        (Y, X) float32 ...
Dimensions without coordinates: X, Y, time_1day
Data variables: 
SnowFall        (Y, X) float32 ...
...
Attributes:
    time_coverage_end:  2019-01-01_23:00:00
    xllcorner:          6.44917
    yllcorner:          43.95483
    xcellsize:          0.009
    ycellsize:          0.009
    nrows:              309
    ncols:              689
```

When loading this dataset with `dc.load(product=product)` it looks like this:

```
<xarray.Dataset>
Dimensions:      (latitude: 309, longitude: 688, time: 1)
Coordinates:
  * time         (time) datetime64[ns] 2019-01-01T23:00:00
  * latitude     (latitude) float64 46.73 46.72 46.71 ... 43.98 43.97 43.96
  * longitude    (longitude) float64 6.457 6.466 6.475 ... 12.62 12.63 12.64
    spatial_ref  int32 4326
Data variables:
  snowfall     (time, latitude, longitude) float32 -9.999e+03 ... -9.999e+03
  ...
Attributes:
    crs:           EPSG:4326
    grid_mapping:  spatial_ref
```
So the dimensions are now `latitude` and `longitude` instead of `X` and `Y`. 

### Steps to reproduce the behaviour

To index the dataset into ODC I use the following product definition

```yml

name: hmc
description: todo
metadata_type: eo3

storage:
  crs: "EPSG:4326"
  resolution:
    longitude: 0.009
    latitude: -0.009

metadata:
  product:
    name: hmc

measurements:
  - name: snowfall
    aliases: [ SnowFall, Snowfall ]
    units: "mm"
    dtype: float32
    nodata: -9999

...
```
and dataset definition

```yml
$schema: https://schemas.opendatacube.org/dataset
product:
  name: hmc
crs: epsg:4326
geometry:
  coordinates:
  - - - 6.453670024871826
      - 46.73133087158203
    - - 6.453670024871826
      - 43.95933151245117
    - - 12.645669937133789
      - 43.95933151245117
    - - 12.645669937133789
      - 46.73133087158203
    - - 6.453670024871826
      - 46.73133087158203
  type: Polygon
grids:
  default:
    shape:
    - 689
    - 309
    transform:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
properties:
  datetime: 2019-01-01 23:00:00
id: 6e0410a6-42a6-425c-80a4-ead4d5d224c4
lineage: {}
measurements:
  snowfall:
    band: 1
    layer: SnowFall
    path: /data/S3M_201901012300.nc
...
```
Additionally I know that geotransformation is not properly set in the file (transform matrix is wrong) but I hope this does not affect this issue.

### Environment information

* Which ``datacube --version`` are you using? datacube 1.8.3
* What datacube deployment/enviornment are you running against? Local setup with pip and database running in docker 

Do you have an idea how I can fix this?

**Comment by Kirill888** [comment]
@sophieherrmann this behaviour is expected. `dc.load` does not do "native projection" loads. In the general case `dc.load` needs to reconcile data from different datasets in different projections/resolutions and present this as a single data stack, this requires picking output projection, resolution and alignment of pixels. Currently this is done by the user via `output_crs=, resolution=, alignment=`  or `like=` parameters, it can also be defined at product creation, like in your case. Since your product has `storage` section defined, like so

```yaml
storage:
  crs: "EPSG:4326"
  resolution:
    longitude: 0.009
    latitude: -0.009
```

`dc.load` will load data into `EPSG:4326` projection using resolution `0.009` degrees per pixel, placing pixel boundaries at `lon=0,lat=0` lines, unless requested to do otherwise via parameters mentioned above. And yes `dc.load` uses names of axis from the projection CRS rather than always returning X,Y. Honestly I would prefer it didn't, and just used x,y all the time, but that would be a backwards incompatible change, although we should probably support that mode as an opt in.
