### ISSUE TITLE
Ingester shouldn't generate empty storage units

### ISSUE THREAD

**Issue by v0lat1le** [opendatacube/datacube-core#121]
Empty storage units (filled with NDV's) are generated for the corners of landsat scene.

Benefits are:
- improved storage access performance
- improved analysis performace
- reduced alaysis memory usage
- reduced file count

**Comment by v0lat1le** [comment]
Usable data polygon needs to be supplied to the ingester. Possible ways of doing this:
1. provide in the dataset metadata (detect during preparation)
2. detect at indexing time
3. detect at ingestion

**Comment by simonaoliver** [comment]
In terms of valid data polygon - for a clunky one liner use gdalpolygonize.py - http://www.gdal.org/gdal_polygonize.html 

**For netcdf**

``` bash
for i in <inputpath>/*.nc ; do  gdal_calc.py -A `gdalinfo $i | grep SUBDATASET_1_NAME= | cut -d "=" -f2` --NoDataValue=-999 --calc=A/A --type=Byte --outfile=$i.tif ; gdal_polygonize.py $i.tif -f 'ESRI Shapefile' $i.shp; done
```

**For tif**

``` bash
for i in <inputpath>/* ; do gdal_calc.py -A `ls -d $i | grep B1.TIF` --NoDataValue=0 --calc=A/A --type=Byte --outfile=/short/v10/sao547/tmp/working.tif ; gdal_polygonize.py working.tif -f 'ESRI Shapefile' /short/v10/sao547/tmp/working.tif.shp; done
```

Note that the valid data extent for each Landsat band is different so would have to be done bandwise or from a band aggregation i.e vrt of all bands.

**Comment by sixy6e** [comment]
I've just uploaded the old method into eotools

https://github.com/GeoscienceAustralia/eo-tools/blob/develop/eotools/vector.py#L74

**Comment by v0lat1le** [comment]
How about adding a field to `grid_spatial/projection` defining the region of valid data:

``` yaml
id: c44cf2b2-e1d0-11e5-b75a-a0000100fe80
label: LS5_TM_NBAR_P54_GANBAR01-002_090_084_20060125
# SNIP usual stuff
grid_spatial:
  projection:
    valid_data:
      type: Polygon
      coordinates: [[[12,34],[56,78],[90,91],[12,34]]]
# SNIP more stuff
```

specified using geojson format in the native projection of the image
