### ISSUE TITLE
datacube dataset search console display should show datetime or center_dt

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-core#1264]
### Expected behaviour

```
root@e2ea6f2165ae:/code# datacube dataset search id = '35cbccee-cb07-51cf-85d2-6d2948957545'
id: 35cbccee-cb07-51cf-85d2-6d2948957545
product: rainfall_chirps_daily
status: active
locations:
- file://example.com/test_dataset/
fields:
    cloud_cover: null
    creation_time: 2021-12-17 02:30:32.725683+00:00
    crs_raw: epsg:4326
    dataset_maturity: null
    format: GeoTIFF
    instrument: null
    label: null
    lat: {begin: -40.000001192092896, end: 40.0}
    lon: {begin: -20.0, end: 55.00000111758709}
    platform: null
    product_family: null
    region_code: null
    time: {begin: '2019-05-15T00:00:00+00:00', end: '2019-05-31T23:59:59+00:00'}
    datetime/center_dt: 'timestring Tblah'
```

### Actual behaviour

`datacube dataset search` only return time, and not `center_dt` or `datetime`

```
root@e2ea6f2165ae:/code# datacube dataset search id = '35cbccee-cb07-51cf-85d2-6d2948957545'
id: 35cbccee-cb07-51cf-85d2-6d2948957545
product: rainfall_chirps_daily
status: active
locations:
- file://example.com/test_dataset/
fields:
    cloud_cover: null
    creation_time: 2021-12-17 02:30:32.725683+00:00
    crs_raw: epsg:4326
    dataset_maturity: null
    format: GeoTIFF
    instrument: null
    label: null
    lat: {begin: -40.000001192092896, end: 40.0}
    lon: {begin: -20.0, end: 55.00000111758709}
    platform: null
    product_family: null
    region_code: null
    time: {begin: '2019-05-15T00:00:00+00:00', end: '2019-05-31T23:59:59+00:00'}
```
### Steps to reproduce the behaviour

run `datacube dataset search` in any established odc environment

### Environment information

* Which ``datacube --version`` are you using?
```
root@e2ea6f2165ae:/code# datacube --version
Open Data Cube core, version 1.8.6
```

* What datacube deployment/enviornment are you running against?
- test environment
