### ISSUE TITLE
Installation of agdc on CentOS machine

### ISSUE THREAD

**Issue by hkristen** [opendatacube/datacube-core#167]
Hi guys! 

I am struggling to install the AGDC2 on a CentOS 7 machine. 

I followed your installation guideline for Ubuntu and everything works fine until I come to the part with the binary python packages. As suggested I used the miniconda2 package manager and with a manually compiled GDAl 2.1.0 version for CentOS (including python & GEOS), the indexing operation is working. 
Unfortunately, as soon as I try to ingest the data to the datacube I get an error that the GDAL version from the conda repo doesn´t support GEOS ... if I install gdal from the conda-forge repo this feature is available, unfortunately rasterio is not working together with this version at it depends on the “original” conda gdal version... 

Has anybody figured out how to install the agdc2 on CentOS?

Any help would be much appreciated!

**Comment by v0lat1le** [comment]
We use packages from `conda-forge` channel.

Out deployment script adds `conda-forge` as default channel :
```shell
conda config --prepend channels conda-forge --system
conda update --all -y
conda env create --file env.yaml
```

env.yaml would be something like:
```yaml
name: datacube
dependencies:
- python=3.5
- bottleneck
- cachetools
- click
- dask
- gdal >=1.9
- jsonschema
- netcdf4
- numpy
- pathlib
- pandas
- pip
- psycopg2
- python-dateutil
- pyyaml
- rasterio
- singledispatch
- sqlalchemy
- xarray
- pip:
  - ciso8601
  - pypeg2
```
plus whatever else you need (`jupiter, matplotlib, scipy, scikit-*`)
