### ISSUE TITLE
Amazon S3 support

### ISSUE THREAD

**Issue by adriaat** [opendatacube/datacube-core#323]
When running Open Data Cube in the cloud, I would like to have datasets in Amazon S3 buckets without having to store them in my EC2 instance. I have seen that in datacube-core release 1.5.2 the new features
* Support for AWS S3 array storage
* Driver Manager support for NetCDF, S3, S3-file drivers

were added. I have read the few documentation there is on these features but I am confused. Is there any documentation on what these features are capable of or any example on how to use them?

**Comment by woodcockr** [comment]
These are new features being developed by the CSIRO contributors to ODC, @petewa and @rtaib . We are currently working on an AWS based ODC execution engine to  support large scale parallel processing, which directly exploits the AWS S3 storage driver. Documentation is a little sparse at the moment but the S3 storage driver is a drop in replacement for the default file based driver. There's a optional flag on the necessary API calls (like datacube.load, the ingester, etc) which tells the system to use the S3 driver. The storage driver handling is documented [here](http://datacube-core.readthedocs.io/en/latest/dev/driver.html) but I suspect you already found that. We are working on a technical paper about the driver which should be available in January.

I will let @petewa know about this thread if he hasn't already spotted it. Let us know your specific questions here and we'll respond.

**Comment by petewa** [comment]
Hi @adriaat,

As @woodcockr mentions, documentation is sparse and is something we need to improve.

The S3 driver extension serves 2 core purposes:
 - Allow ODC to ingest directly to S3 and have ODC operates as before while storing & retrieving data from S3 transparently.
 - High performance externally indexed ndarray storage back-end for scalable compute on the cloud.
   - use S3 like raw main memory (key = memory address, object = contiguous block of binary data)

In more detail:
 - ODC ingest directly to S3 and you can use ODC as before.
   - ODC able to store arrays distributed to S3 objects in a compute usable format.
 - ODC able to query/retrieve arrays direct from S3.
   - ODC able to parallelise IO to/from S3 for Data Access/Storage.
 - S3 IO is done in parallel streams into a shared memory array without locking.
 - Data in S3 are nd mapped to 1D, so for a given nd data request, you know in advance where data is.
   - For a given nd query, you can map out the required IO operations before hitting S3.
     - useful for keeping the compute pipeline full.
     - this feeds into data decomposition for compute more on that later.
  - data is stored as chunked row-major and compressed.
     - data in nd space is close in 1d space.

Things in store for the future:
 - reduced memory consumption with optimised threads/process scaling for ec2 cluster
   - already in csiro/execution-engine branch, not yet in develop
 - improved stability with multiple threads/process
   - already in csiro/execution-engine branch, not yet in develop
 - lazy arrays for accessing data on s3 as though it's a local array.
   - already in csiro/execution-engine branch, not yet in develop
 - moving from postgres index to a memory cached n-dimensional index for index and storage.
   - Hilbert curve for mapping nd data to 1D
 - storing multiple chunks in s3 object.
 - ODC data access API to support nd block retrieval.
   - currently only 2D block retrieval and stacking over time.

S3 Ingestion:

I am assuming you are already familiar with the ingest process using the default NetCDF driver.

I'll cover the differences when ingesting to S3:

1. You will need an AWS account and a .aws/credentials file:

```
[default]
aws_access_key_id = <Access key ID>
aws_secret_access_key = <Secret access key>
```

2. Initialise the database with an extra s3 flag. This creates the extra tables in the database for s3.

`datacube -v system init -s3`

3. Example ingest config yaml with extra s3 parameters

```
docs/config_samples/ingester/ls5_nbar_albers_s3.yaml

Settings which you will need to change/add:
container: bucket_name  (must exist prior to ingest)
storage:
  driver: s3 (select s3 driver)
```

4. Ingest with an extra s3 parameter -- driver s3. This tells ODC to use the s3 driver for ingest.
```
datacube --driver s3 -v ingest -c ~/yamls/ls5_nbar_albers_s3.yaml --executor multiproc 8

Usage:

Usage is the same except you now are able to use the use_threads option in datacube.load(). This will parallelise the data access from S3.

e.g.
import datacube
dc = datacube.Datacube()
nbar = dc.load(product='ls5_nbar_albers', x=(149, 150), y=(-35, -36), use_threads=True)
```

**Comment by davidedelerma** [comment]
Hi,

Many thanks for your help. 
I am working with @adriaat on OpenDataCube and I am experiencing the same issue of configuring datacube with S3.

When I run the command:  `datacube -v system init --create-s3-tables`
I got the following message:

2017-11-17 17:52:21,845 3828 datacube INFO Running datacube command: /home/ubuntu/Datacube/datacube_env/bin/datacube -v system init -s3
2017-11-17 17:52:21,855 3828 DriverManager INFO Import Failed for Driver plugin "S3TestDriver", skipping.
2017-11-17 17:52:21,856 3828 DriverManager INFO Import Failed for Driver plugin "S3Driver", skipping.
Initialising database...
2017-11-17 17:52:21,862 3828 datacube.index.postgres.tables._core INFO Ensuring user roles.
2017-11-17 17:52:21,865 3828 datacube.index.postgres.tables._core INFO Adding role grants.
Updated.
Checking indexes/views.
2017-11-17 17:52:21,871 3828 datacube.index.postgres._api INFO Checking dynamic views/indexes. (rebuild views=True, indexes=False)
Done.

So the new tables in Postgres for S3 cannot be created.
The aws credentials are properly set in .aws/credentials file
I am working on the develop branch and the Datacube version is :  1.5.1+218.g5f8507c
Same error happens in CSIRO branch.

Thanks,
Davide

**Comment by petewa** [comment]
Hi Davide,

The import failed message is not worded very well. You can safely ignore it. Non default drivers are skipped during initialization because they are not required. In this particular case, they are skipped because the s3 tables are not present before initialization. After you execute the 'datacube -v system init -s3', the tables should be properly created and initialized.

You can confirm by checking the following tables are created:
- s3_dataset
- s3_dataset_chunk
- s3_dataset_mapping

Thanks,
Peter

**Comment by davidedelerma** [comment]
Hi @petewa ,

I double checked, but unfortunately there are not new tables into the database.
The only tables in the agdc schema are:
- dataset
- dataset_location
- dataset_source
- dataset_type
- metadata_type

Thanks,
Davide

**Comment by petewa** [comment]
Hi @davidedelerma, could you please try the 'datacube -v system init -s3' command with a fresh database.

The init script may not be set up to create the tables with an already initialised agdc schema.

**Comment by davidedelerma** [comment]
Hi @petewa ,
Thanks.
I dropped the database and initialized it again using the "s3" option.
Now I have the three extra tables.
Then I added a product (Landsat 8) and indexed 9 Landsat 8 L2 images referring to the same footprint.
After that I modified the configuration file for ingestion using:
```
container: 'rheaodc'
storage:
  driver: s3
```
but when I run the command:
`datacube --driver s3 -v ingest -c ~/ls8_collections_sr_general_s3.yaml `
I get the error:
```
2017-11-21 13:12:41,883 1935 datacube INFO Running datacube command: /home/ubuntu/Datacube/datacube_env/bin/datacube --driver s3 -v ingest -c /home/ubuntu/ls8_collections_sr_general_s3.yaml
2017-11-21 13:12:41,897 1935 DriverManager INFO Import Failed for Driver plugin "S3TestDriver", skipping.
2017-11-21 13:12:41,898 1935 DriverManager INFO Import Failed for Driver plugin "S3Driver", skipping.
Traceback (most recent call last):
  File "/home/ubuntu/Datacube/datacube_env/bin/datacube", line 11, in <module>
    load_entry_point('datacube', 'console_scripts', 'datacube')()
  File "/home/ubuntu/Datacube/datacube_env/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", lin                                                               e 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/Datacube/datacube_env/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", lin                                                               e 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/Datacube/datacube_env/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", lin                                                               e 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/Datacube/datacube_env/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", lin                                                               e 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/Datacube/datacube_env/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", lin                                                               e 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/ui/click.py", line 199, in new_func
    return f(parsed_config, *args, **kwargs)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/ui/click.py", line 226, in with_driver_manager
    validate_connection=expect_initialised) as driver_manager:
  File "/home/ubuntu/Datacube/agdc-v2/datacube/drivers/manager.py", line 78, in __init__
    self.set_current_driver(default_driver_name or self._DEFAULT_DRIVER)
  File "/home/ubuntu/Datacube/agdc-v2/datacube/drivers/manager.py", line 198, in set_current_driver
    driver_name, ', '.join(self.__drivers.keys())))
ValueError: Default driver "s3" is not available in NetCDF CF
```
Thanks, 
Davide

**Comment by davidedelerma** [comment]
Here is the full configuration file for ingestion:
```yaml
source_type: ls8_collections_sr_scene
output_type: ls8_lasrc_general_s3

description: Landsat 8 USGS Collection 1 Higher Level SR scene proessed using LaSRC. Resampled to 30m EPSG:4326 projection with a sub degree tile size.

location: '/datacube/ingested_data'
file_path_template: 'LS8_OLI_LaSRC/General/LS8_OLI_LaSRC_4326_{tile_index[0]}_{tile_index[1]}_{start_time}.nc'
global_attributes:
  title: CEOS Data Cube Landsat Surface Reflectance
  summary: Landsat 8 Operational Land Imager ARD prepared by NASA on behalf of CEOS.
  source: LaSRC surface reflectance product prepared using USGS Collection 1 data.
  institution: CEOS
  instrument: OLI_TIRS
  cdm_data_type: Grid
  keywords: AU/GA,NASA/GSFC/SED/ESD/LANDSAT,REFLECTANCE,ETM+,TM,OLI,EARTH SCIENCE
  keywords_vocabulary: GCMD
  platform: LANDSAT_8
  processing_level: L2
  product_version: '2.0.0'
  product_suite: USGS Landsat Collection 1
  project: CEOS
  coverage_content_type: physicalMeasurement
  references: http://dx.doi.org/10.3334/ORNLDAAC/1146
  license: https://creativecommons.org/licenses/by/4.0/
  naming_authority: gov.usgs
  acknowledgment: Landsat data is provided by the United States Geological Survey (USGS).

container: 'rheaodc'
storage:
  driver: s3

  crs: EPSG:4326
  tile_size:
          longitude: 0.943231048326
          latitude:  0.943231048326
  resolution:
          longitude: 0.000269494585236
          latitude: -0.000269494585236
  chunking:
      longitude: 200
      latitude: 200
      time: 1
  dimension_order: ['time', 'latitude', 'longitude']

measurements:
    - name: coastal_aerosol
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band1'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.43-0.45 microns (Coastal Aerosol)"
          alias: "band_1"
    - name: blue
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band2'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.45-0.51 microns (Blue)"
          alias: "band_2"
    - name: green
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band3'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.53-0.59 microns (Green)"
          alias: "band_4"
    - name: red
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band4'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.64-0.67 microns (Red)"
          alias: "band_4"
    - name: nir
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band5'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.85-0.88 microns (Near Infrared)"
          alias: "band_5"
    - name: swir1
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band6'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 1.57-1.65 microns (Short-wave Infrared)"
          alias: "band_6"
    - name: swir2
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band7'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 2.11-2.29 microns (Short-wave Infrared)"
          alias: "band_7"
    - name: 'pixel_qa'
      dtype: int32
      nodata: 1
      resampling_method: nearest
      src_varname: 'pixel_qa'
      zlib: True
      attrs:
          long_name: "Pixel Quality Attributes Bit Index"
          alias: [pixel_qa]
    - name: 'aerosol_qa'
      dtype: uint8
      nodata: 0
      resampling_method: nearest
      src_varname: 'sr_aerosol'
      zlib: True
      attrs:
          long_name: "Aerosol Quality Attributes Bit Index"
          alias: [sr_aerosol_qa, sr_aerosol]
    - name: 'radsat_qa'
      dtype: int32
      nodata: 1
      resampling_method: nearest
      src_varname: 'radsat_qa'
      zlib: True
      attrs:
          long_name: "Radiometric Saturation Quality Attributes Bit Index"
          alias: [radsat_qa]
    - name: 'solar_azimuth'
      dtype: int16
      nodata: -32768
      resampling_method: nearest
      src_varname: 'solar_azimuth_band4'
      zlib: True
      attrs:
          long_name: "Solar Azimuth Angle for Band 4"
          alias: [solar_azimuth_band4]
    - name: 'solar_zenith'
      dtype: int16
      nodata: -32768
      resampling_method: nearest
      src_varname: 'solar_zenith_band4'
      zlib: True
      attrs:
          long_name: "Solar Zenith Angle for Band 4"
          alias: [solar_zenith_band4]
    - name: 'sensor_azimuth'
      dtype: int16
      nodata: -32768
      resampling_method: nearest
      src_varname: 'sensor_azimuth_band4'
      zlib: True
      attrs:
          long_name: "Sensor Azimuth Angle for Band 4"
          alias: [sensor_azimuth_band4]
    - name: 'sensor_zenith'
      dtype: int16
      nodata: -32768
      resampling_method: nearest
      src_varname: 'sensor_zenith_band4'
      zlib: True
      attrs:
          long_name: "Sensor Zenith Angle for Band 4"
          alias: [sensor_zenith_band4]

```

**Comment by petewa** [comment]
Hi @davidedelerma,

I made a mistake in my earlier post.
"Import Failed for Driver plugin "S3Driver", skipping." Should not be happening.
This means that there was an import error when loading the the S3Driver.

In relation to my earlier message. I misread it as "Driver plugin "S3Driver" failed requirements check, skipping" which is different.

It looks like you are on EC2 with a flavor of Ubuntu. What version of Ubuntu? I've been using 'Ubuntu 16.04.1 LTS' personally.
Can you please post the output from pip freeze.

The following should give you the proper environment:
```
conda config --prepend channels conda-forge
conda config --prepend channels conda-forge/label/dev
conda create -n agdc python=3.6
conda env update -n agdc --file datacube-core/.travis/environment.yaml
source activate agdc
```

**Comment by petewa** [comment]
Greetings @davidedelerma 

How did you go?

**Comment by adriaat** [comment]
Hello all,

@davidedelerma and I have been working on it. We both use Ubuntu 16.04.03 LTS. We created a new environment following @petewa commands from a previous comment. Using this environment, we ingested a single time slice of Landsat 8 data in a S3 bucket. There was no error in the ingestion. We loaded this data with `use_threads=False` and we did not have any problem: the data is correctly loaded, even though it is slow. Surprisingly, the instance we used had 4 vcpu, and the 4 of them were being used in the ingestion process. On the other hand, we also tried loading the data with `use_threads=True`. In this case, the jupyter notebook never finishes (at least for a reasonable amount of waiting time) loading the data, and the consumption of the vcpus is nearly 0.

In the same environment, we ingested two time slices of Landsat 8 data. We loaded these data using `use_threads=False` and `use_threads=True`, and in both cases we were able to load it. Afterwards, we ingested more data and we had in total 9 time slices of Landsat 8 data. We loaded a region of interest of these 9 time slices, due to limitations with memory, but we did not have any problem as well.

We tested all of the above with both develop and csiro/execution-engine branches, where the two yield datacube version 1.5.1.

At this point, we ask ourselves
1. What are the advantages of storing the ingested data as objects in S3 with respect to using S3 buckets as a file system for ingested data by means of software that allows to mount S3 buckets, e.g. [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse)?
2. How does `use_threads` actually paralellise the data access from S3? Since when we used `use_threads=False` we saw that our all vcpus were being used.

Elaborating on the point 2, we did a small benchmark of the elapsed time when loading the ingested data for a region of interest for the 9 time slices, when ingested in the S3 using the s3 driver and when ingested locally, and also testing the develop and the csiro/execution-engine branches. The results show the average time over 3 runs.

|                      | Branch develop                                            | Branch csiro/execution-engine                             |
|----------------------|-----------------------------------------------------------|-----------------------------------------------------------|
| In S3 with s3 driver | `use_threads=False`: 33.24 s, `use_threads=True`: 25.29 s | `use_threads=False`: 83.08 s, `use_threads=True`: 72.64 s |
| In EC2               | `use_threads=False`: 6.71 s, `use_threads=True`: 6.45 s   | `use_threads=False`: 6.63 s, `use_threads=True`: 6.22 s   |

We expected some problem if we loaded the ingested data in EC2 using `use_threads=True`, given a previous comment. However, it works and it is faster! On the other hand, we are also surprised to see that the csiro/execution-engine branch is faster when loading the ingested data in EC2 but much slower when the data is in S3.

There is something else that may be worth sharing. The environment we were using before was the one created by following the installation guide for Open Data Cube in the [www.opendatacube.org](https://www.opendatacube.org/data-cube-installation) website: [Data Cube Installation Guide](https://github.com/ceos-seo/data_cube_ui/blob/master/docs/datacube_install.md). However, when using the environment created with the environment file `datacube-core/.travis/environment.yaml`, there is an error with the postgres database that before we did not have:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```
Before we did not have a `db_hostname` in the `.datacube.conf` file. To solve this error, we had to set either `db_hostname: localhost` or `db_hostname: /var/run/postgresql` in the `.datacube.conf` file.

**Comment by petewa** [comment]
1. One thing that comes to mind is latency and compute performance. There are a bunch of reasons, main one being AWS architects tends steer us away from using s3 as a file system e.g. s3fs

2. use_threads controls the threading on retrieving multiple time slices and stitching datasets. This is currently a compromise. Having said that, the underlying S3IO library is threaded by default.

Regarding your benchmarks, with a 200x200 chunking size, I'm not surprised with the results you are seeing.

Try these parameters for S3 as a starting point and tweak from there.
 - change chunking to 2000x2000
 - change tile size and resolution such that a tile is roughly 8000x8000 or more

Example LS5 ingest config.
https://github.com/opendatacube/datacube-core/blob/develop/docs/config_samples/ingester/ls5_nbar_albers_s3.yaml

I aim for objects around ~10-20 MB in size. You can look in your S3 bucket to see this, post ingest.

use_threads should not make a difference when ingesting to EBS with the default netcdf driver.
use_threads should make a big difference when ingesting to EBS with the s3-file driver.

The csiro/csiro-execution engine branch tries to balance performance with memory consumption.
It scales the number of threads w.r.t to the number of cores. It's something like:
threads = ncores*2 for stitching/stacking.
processes =  ncores for pulling data from s3.

**Comment by adriaatrhea** [comment]
Hello,

Thank you for your reply @petewa. I played a little bit with the suggested changes and with the two branches (`develop` and `csiro/execution-engine`), producing benchmarks to qualify and quantify the results. Since there are just too many results to post them here, I give an overall impression of them. The comments below refer to loading times of 9 Lansat 8 time slices, sharing the comments for both branches (unless specified otherwise) and in an Amazon EC2 t2.xlarge instance (vcPU: 4, memory: 16 GiB). Also, please note that when I refer to "tile size" I am referring to the ratio "tile size/resolution" (I did not change the resolution), and when referred to a chunking parameter, the chunks are squared (therefore a chunking parameter of `200` stands for `200x200`).
* If only the chunking parameter is changed from the original `200` to `2000`: the loading time is much faster (40%-85% faster!), specially if `use_threads=True`.
* If only the tile size is changed from `3500` to `8000`: it is faster, but much slower than only changing the chunking parameter from `200` to `2000`.
* If both the tile size is changed from `3500` to `8000` and the chunking parameter from `200` to `2000`: it is faster, but the loading times are similar to only changing the chunking parameter, as if the tile size did not have an enhancing effect.
* Having played with the above parameters, the largests files in the bucket are slighly larger than 5 MB. I guess other parameters should be used to obtain objects around 10-20 MB in size.
* When ingesting to the EBS, there is not a clear difference with `use_threads` with either the default NetCDF driver or the S3-file driver.
  The way I ingest to the EBS with the S3-file driver is the following:  
  * For each ingestion configuration file (so different tile sizes and chunkings) I set `driver: s3` in the `storage:` list, i.e.
    ```
    storage:
        driver: s3
        crs: EPSG:4326
        tile_size:
            longitude: 0.943231048326
            latitude:  0.943231048326
        resolution:
            longitude: 0.000269494585236
            latitude: -0.000269494585236
        chunking:
            longitude: 200
            latitude: 200
            time: 1
        dimension_order: ['time', 'latitude', 'longitude']
    ``` 
  * Ingest with the usual command, `datacube -v ingest -c ~/ls8_test.yaml`. If I run `datacube --driver s3 -v ingest -c ~/ls8_test.yaml`, I get the error `datacube.utils.DatacubeException: Missing 'container' parameter, cannot write to storage.` I understand that, if I set the container parameter, the data will be ingested to the S3 bucket rather than into the EBS. Am I right?
* When ingesting to S3, the branches `develop` and `csiro/execution-engine` result approximately equal in timewise terms, except when the chunking parameter is set small, i.e. `200`, regardless of the tile size. In these cases, the differences are like the ones in the table of my previous comment.
* The fastest loading times from data ingested in the S3 bucket is given by the branch develop, with `use_threads=True`, and with chunking set to `2000`, regardless of the tile size. It is also quicker to load data chunked to `2000` with `use_threads=False` than data chunked to `200` and `use_threads=True`.

Now everything makes more sense. @petewa says in the previous comment that `use_threads` should make a big difference when ingesting to EBS with the S3-file driver, in contrast with using the default NetCDF driver. However, I do not experience this behaviour and it may come from my side. Did I ingest the files correctly to the EBS using the S3 driver? I only have NetCDF files in the ingestion directory specified for the S3-file driver, is that OK?

**Comment by adriaat** [comment]
Hello,

Thank you for your reply @petewa. I played a little bit with the suggested changes and with the two branches (`develop` and `csiro/execution-engine`), producing benchmarks to qualify and quantify the results. Since there are just too many results to post them here, I give an overall impression of them. The comments below refer to loading times of 9 Lansat 8 time slices, sharing the comments for both branches (unless specified otherwise) and in an Amazon EC2 t2.xlarge instance (vcPU: 4, memory: 16 GiB). Also, please note that when I refer to "tile size" I am referring to the ratio "tile size/resolution" (I did not change the resolution), and when referred to a chunking parameter, the chunks are squared (therefore a chunking parameter of `200` stands for `200x200`).
* If only the chunking parameter is changed from the original `200` to `2000`: the loading time is much faster (40%-85% faster!), specially if `use_threads=True`.
* If only the tile size is changed from `3500` to `8000`: it is faster, but much slower than only changing the chunking parameter from `200` to `2000`.
* If both the tile size is changed from `3500` to `8000` and the chunking parameter from `200` to `2000`: it is faster, but the loading times are similar to only changing the chunking parameter, as if the tile size did not have an enhancing effect.
* Having played with the above parameters, the largests files in the bucket are slighly larger than 5 MB. I guess other parameters should be used to obtain objects around 10-20 MB in size.
* When ingesting to the EBS, there is not a clear difference with `use_threads` with either the default NetCDF driver or the S3-file driver.
  The way I ingest to the EBS with the S3-file driver is the following:  
  * For each ingestion configuration file (so different tile sizes and chunkings) I set `driver: s3` in the `storage:` list, i.e.
    ```
    storage:
        driver: s3
        crs: EPSG:4326
        tile_size:
            longitude: 0.943231048326
            latitude:  0.943231048326
        resolution:
            longitude: 0.000269494585236
            latitude: -0.000269494585236
        chunking:
            longitude: 200
            latitude: 200
            time: 1
        dimension_order: ['time', 'latitude', 'longitude']
    ``` 
  * Ingest with the usual command, `datacube -v ingest -c ~/ls8_test.yaml`. If I run `datacube --driver s3 -v ingest -c ~/ls8_test.yaml`, I get the error `datacube.utils.DatacubeException: Missing 'container' parameter, cannot write to storage.` I understand that, if I set the container parameter, the data will be ingested to the S3 bucket rather than into the EBS. Am I right?
* When ingesting to S3, the branches `develop` and `csiro/execution-engine` result approximately equal in timewise terms, except when the chunking parameter is set small, i.e. `200`, regardless of the tile size. In these cases, the differences are like the ones in the table of my previous comment.
* The fastest loading times from data ingested in the S3 bucket is given by the branch develop, with `use_threads=True`, and with chunking set to `2000`, regardless of the tile size. It is also quicker to load data chunked to `2000` with `use_threads=False` than data chunked to `200` and `use_threads=True`.

Now everything makes more sense. @petewa says in the previous comment that `use_threads` should make a big difference when ingesting to EBS with the S3-file driver, in contrast with using the default NetCDF driver. However, I do not experience this behaviour and it may come from my side. Did I ingest the files correctly to the EBS using the S3 driver? I only have NetCDF files in the ingestion directory specified for the S3-file driver, is that OK?
