### ISSUE TITLE
Silent dataset location modification when using `datacube dataset <add|update>`

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#446]
### Expected behaviour

`datacube dataset add/update` should report that a new dataset location was recorded in the database.

### Actual behaviour

`datacube -vv dataset add` reports:

```
WARNING Duplicate dataset, not inserting: f5b8dfa5-47c5-489d-ab2f-d518c72d8a70
```

while `datacube -vv dataset update` reports:

```
INFO No changes detected for dataset f5b8dfa5-47c5-489d-ab2f-d518c72d8a70
```

Yet dataset location is modified as can be confirmed by `datacube dataset info`

```
id: f5b8dfa5-47c5-489d-ab2f-d518c72d8a70
product: ls8_nbar_albers
status: active
indexed: 2017-09-07 15:36:39.485455+10:00
locations:
- file:///Users/kirill/datacube/ls8_nbar_pq/tmp2.nc
- file:///Users/kirill/datacube/ls8_nbar_pq/tmp.nc
- file:///Users/kirill/datacube/ls8_nbar_pq/LS8_OLI_NBAR_3577_5_-37_20161005003349000000.nc                                                                  
fields:
    format: NetCDF
    instrument: OLI_TIRS
    lat: {begin: -33.77978845211354, end: -33.54258935760496}
    lon: {begin: 138.1793664303201, end: 138.5168418084227}
    platform: LANDSAT_8
    product_type: nbar
    time: {begin: '2016-10-05T00:33:49', end: '2016-10-05T00:33:49'}
```

### Steps to reproduce the behaviour

In a test database find some dataset, make a copy of the netcdf file. Call `datacube -vv dataset add` on the copy. Then run `datacube dataset info <uuid>` and observe that locations part has been augmented with a new file.
