### ISSUE TITLE
Support lighter-weight lineage tracking in `dataset add`

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#471]
Currently `datacube dataset add` expects that metadata document for dataset being indexed includes full metadata document for every dataset in its direct lineage, and these in turn, recursively, include all the metadata documents for their lineage and so on. This approach has certain data integrity, and data distribution advantages and works relatively well for simple transforms, like `scene->nbar_scene->nbar_albers->fc`. However, it becomes quite cumbersome for full-history statistical products like geometric median, metadata document grows really large quickly. 

I propose we allow uuid-only lineage to be accepted as an alternative. This still records full lineage of a generated dataset at the time of computation, but relies on access to the original database to translate uuids to actual metadata.

```yaml
id: <uuid>
lineage:
  sources:
     a:
       id: <uuid>
       sources:
         b:
           id: <uuid>
           sources: {}
     c:
      id: <uuid>
      sources: {}
```

Essentially this encodes an N-way tree (constructed from Directed Acyclic Graph, which is the real lineage dependency structure), where each node has `id` property and a dictionary of named sources that contain more nodes. Use of dictionary instead of just a list is to be consistent with the way we capture this information currently.

When you add dataset with lightweight lineage data to the datacube the expectation is that all referenced datasets are already present in the database.
