### ISSUE TITLE
Handling of NaN values during indexing

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#524]
On NCI install, `NaN` values get stored as strings in the DB.

Some scenes in the `ls8_level1_scene` have `NaN` values in the `gqa` subtree, they appear correctly in the yaml document, but appear as strings in the database:

- uuid: `d30ebe7e-237f-4783-af03-90ef91bc081d`
- file: `/g/data/v10/reprocess/ls8/level1/2018/05/LS8_OLITIRS_OTH_P41_GALPGS01-032_088_078_20180504/ga-metadata.yaml`

File on disk has proper `.nan` and loads in python with `yaml.safe_load` giving `NaN`:

```yaml
id: d30ebe7e-237f-4783-af03-90ef91bc081d
ga_label: LS8_OLITIRS_OTH_P41_GALPGS01-032_088_078_20180504
product_type: level1
product_level: L1GT
creation_dt: 2018-07-09 11:08:01
...
gqa:
    error_message: No reference or backup reference imagery available.
    final_gcp_count: 0
    ref_date: null
    ref_source: null
    ref_source_path: null
    residual:
        abs:
            x: .nan
            xy: .nan
            y: .nan
        abs_iterative_mean:
            x: .nan
            xy: .nan
            y: .nan
        cep90: .nan
``` 

However data stored in DB has a 3 char string `"NaN"`

```json
{
  "id": "d30ebe7e-237f-4783-af03-90ef91bc081d",
  "gqa": {
    "ref_date": null,
    "residual": {
      "abs": {
        "x": "NaN",
        "y": "NaN",
        "xy": "NaN"
      },
      "abs_iterative_mean": {
        "x": "NaN",
        "y": "NaN",
        "xy": "NaN"
      }
...
  }
...
}
```

This was observed while testing sync tool by @santoshamohan, sync tool *correctly* reports inconsistency between lineage data and DB version.
