### ISSUE TITLE
error creating tasks "temporary file size exceeds temp_file_limit" 8388608kB 

### ISSUE THREAD

**Issue by BexDunn** [opendatacube/datacube-core#559]
### Actual behaviour

This error is happening while I am running `datacube_stats` with a given tile list mentioned below.
The command I am running is:
```bash
 datacube-stats -vvv --tile-index-file $TILE_LIST --save-tasks $TASK $CONFIG
```

### The error I am getting is:

```bash
datacube_stats.main ERROR (psycopg2.OperationalError) temporary file size exceeds temp_file_limit (8388608kB)[SQL: 'WITH RECURSIVE base_query(id, metadata_type_ref, dataset_type_ref, metadata, archived, added, added_by, uris, source_dataset_ref, distance, path) AS \n(SELECT agdc.dataset.id AS id, agdc.dataset.metadata_type_ref AS metadata_type_ref, agdc.dataset.dataset_type_ref AS dataset_type_ref, agdc.dataset.metadata AS metadata, agdc.dataset.archived AS archived, agdc.dataset.added AS added, agdc.dataset.added_by AS added_by, array((SELECT selected_dataset_location.uri_scheme || %(uri_scheme_1)s || selected_dataset_location.uri_body AS anon_1 \nFROM agdc.dataset_location AS selected_dataset_location \nWHERE selected_dataset_location.dataset_ref = agdc.dataset.id AND selected_dataset_location.archived IS NULL ORDER BY selected_dataset_location.added DESC)) AS uris, agdc.dataset_source.source_dataset_ref AS source_dataset_ref, %(param_1)s AS distance, agdc.dataset_source.classifier AS path \nFROM agdc.dataset JOIN agdc.dataset_source ON agdc.dataset.id = agdc.dataset_source.dataset_ref \nWHERE agdc.dataset.archived IS NULL AND (tstzrange(agdc.common_timestamp((agdc.dataset.metadata #>> %(metadata_1)s)), agdc.common_timestamp((agdc.dataset.metadata #>> %(metadata_2)s)), %(tstzrange_1)s) && %(tstzrange_2)s) AND agdc.dataset.dataset_type_ref = %(param_2)s UNION ALL SELECT base_query.id AS id, base_query.metadata_type_ref AS metadata_type_ref, base_query.dataset_type_ref AS dataset_type_ref, base_query.metadata AS metadata, base_query.archived AS archived, base_query.added AS added, base_query.added_by AS added_by, base_query.uris AS uris, agdc.dataset_source.source_dataset_ref AS source_dataset_ref, base_query.distance + %(distance_1)s AS distance, base_query.path || %(path_1)s || agdc.dataset_source.classifier AS path \nFROM base_query JOIN agdc.dataset_source ON base_query.source_dataset_ref = agdc.dataset_source.dataset_ref)\n SELECT DISTINCT base_query.id, base_query.metadata_type_ref, base_query.dataset_type_ref, base_query.metadata, base_query.archived, base_query.added, base_query.added_by, base_query.uris \nFROM base_query JOIN agdc.dataset ON agdc.dataset.id = base_query.source_dataset_ref \nWHERE agdc.dataset.archived IS NULL AND CAST((agdc.dataset.metadata #>> %(metadata_3)s) AS DOUBLE PRECISION) >= %(param_3)s AND CAST((agdc.dataset.metadata #>> %(metadata_4)s) AS DOUBLE PRECISION) < %(param_4)s AND agdc.dataset.dataset_type_ref = %(param_5)s'] [parameters: {'uri_scheme_1': ':', 'param_1': 1, 'metadata_1': '{extent, from_dt}', 'metadata_2': '{extent, to_dt}', 'tstzrange_1': '[]', 'tstzrange_2': DateTimeTZRange(Timestamp('1987-01-01 00:00:00+0000', tz='UTC'), Timestamp('2018-12-31 00:00:00+0000', tz='UTC'), '[)'), 'param_2': 6, 'distance_1': 1, 'path_1': '.', 'metadata_3': '{gqa, residual, iterative_mean, xy}', 'param_3': -1, 'metadata_4': '{gqa, residual, iterative_mean, xy}', 'param_4': 1, 'param_5': 2}] (Background on this error at: http://sqlalche.me/e/e3q8)
```

![image](https://user-images.githubusercontent.com/20038594/45467133-4b6dd500-b761-11e8-931d-7d388cfc127b.png)

### Steps to reproduce the behaviour

Running tci_percentile custom stats for 2012-2017 for the following tiles:
 12 -23
 13 -23
 14 -23
 15 -23
 14 -22
 12 -21
 14 -21
 12 -20
 13 -20
 14 -20
```bash
module use /g/data/v10/public/modules/modulefiles/
module load dea/20180515
export PYTHONPATH=/g/data/r78/datacube_stats:$PYTHONPATH
cd /g/data/r78/datacube_stats/TCW_stats/UB/UB_wet_pct
source  ub_pctwetall.sh
```
(permissions are open)

### ... Include code, command line parameters as appropriate ...

from the yaml file: `ub_wet_pct_all.yaml`

Sources:
```yaml
## Define inputs to perform statistics on
sources:
  - product: ls5_nbar_albers
    measurements: [blue, green, red, nir, swir1, swir2]
    group_by: solar_day
    source_filter:
      product: ls5_level1_scene
      gqa_iterative_mean_xy: [-1, 1]
    masks:
      - product: ls5_pq_albers
        measurement: pixelquality
        group_by: solar_day
        fuse_func: datacube.helpers.ga_pq_fuser
        flags:
          contiguous: True
          cloud_acca: no_cloud
          cloud_fmask: no_cloud
          cloud_shadow_acca: no_cloud_shadow
          cloud_shadow_fmask: no_cloud_shadow
          blue_saturated: False
          green_saturated: False
          red_saturated: False
          nir_saturated: False
          swir1_saturated: False
          swir2_saturated: False
```

### Environment information

* Which ``datacube --version`` are you using?
```bash
Currently Loaded Modulefiles:
  1) pbs                 2) udunits/2.1.24      3) /dea-env/20180405   4) /dea/20180515
[rjd547@raijin3 UB_wet_pct]$ datacube --version
Open Data Cube core, version 1.6rc1+28.ga69dfff5
```

* What datacube deployment/enviornment are you running against?
This is the NCI DEA Production database
