### ISSUE TITLE
Extent extraction is broken for datasets using Geographic CRSs

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/datacube-core#567]
### Expected behaviour

Should be able to define Dataset `grid_spatial` with Geographic CRS, like `EPSG:4326` using `latitude/longitude` keys instead of `y,x` for for `geo_ref_points` construct:

```yaml
'grid_spatial': {'projection': {
'spatial_reference': 'EPSG:4326',
'geo_ref_points': {
    'll': {'latitude': 3.9118399999999993, 'longitude': -71.8432},
    'lr': {'latitude': 3.9118399999999993, 'longitude': -70.84252},
    'ul': {'latitude': 4.912519999999999, 'longitude': -71.8432},
    'ur': {'latitude': 4.912519999999999, 'longitude': -70.84252}},
   }}
```

### Actual behaviour

Fails with `KeyError` in here:

https://github.com/opendatacube/datacube-core/blob/a82de5c031d711043b5dedbb09b609de0d544a4f/datacube/model/__init__.py#L273-L274
