### ISSUE TITLE
QA bit level info machine readability 

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-core#88]
QA bit level info has been added to storage config example ls5_albers.yaml along with longnames containing wavelength info - look into how best to represent this data and modify the yaml accordingly. Also note that cubic has been changed to nearest to enable pixel alignment between GANBAR and PQ products. 

Need to work out how ingester handles QA data to enable parsing - looking at a common method for bit level interpretation towards a common method for mask method filter values/range/bits to mask

**Comment by simonaoliver** [comment]
Also investigating spectral response function inclusion with the aim to enable band equivalence based on spectral response - centre wavelength, and range of acceptable limits for equivalence. Remote Sensing scientists have differing ideas on what constitutes band equivalence so a range could be used for this. i.e. does target sensor have values in range based on spectral response or min/max?

**Comment by v0lat1le** [comment]
I added some in-line comments to 97cbb4f3ceca0acdd49221eb52c4e85b86924aa4
Discuss

**Comment by sixy6e** [comment]
How PQ masking is performed under eotools, https://github.com/GeoscienceAustralia/eo-tools/blob/stable/eotools/pq_utils.py, looks similar to the 'make_mask' function.  Bit values are referenced via a 'look-up-table'.

Under eotools, the assumption is that if a bit is asked for, then a mask corresponding to that bit is generated.  The meaning of True/False is merely to retrieve that bit or ignore and move on.

What eotools also does is provide mask inversion, if a given bit was asked for in the first place.

To me it is a concept of apply or not apply the bit extraction.

The example:

``` yaml
cloud_shadow_fmask:
  bit_index: 13
  value: 0
  description: Cloud Shadow (Fmask)
```

is more straight forward, as the bit mask implies 'feature: create mask for this bit'.  'Not {feature} mask = True' can be kind of confusing.

This approach could work for multiple bit-oriented datasets, if we define that a feature at a given bit is the feature that will be masked out.  PQ eg, Saturation_1 results in a mask with saturated pixels in band one defined as False.

**Comment by omad** [comment]
We have gone with pretty much the above definition. Here's a slightly abbreviated Landsat 5 PQ example:

``` yaml
measurements:
  pixelquality:
      dtype: int16
      units: '1'
      resampling_method: nearest
      src_varname: PQ
      zlib: True
      flags_definition:
          cloud_shadow_fmask:
            bit_index: 13
            value: 0
            description: Cloud Shadow (Fmask)
          cloud_shadow_acca:
            bit_index: 12
            value: 0
            description: Cloud Shadow (ACCA)
          cloud_fmask:
            bit_index: 11
            value: 0
            description: Cloud (Fmask)
          cloud_acca:
            bit_index: 10
            value: 0
            description: Cloud (ACCA)
          land_obs:
            bit_index: 9
            value: 1
            description: Land observation
          sea_obs:
            bit_index: 9
            value: 0
            description: Sea observation
          contiguity:
            bit_index: 8
            value: 1
            description: All bands for this pixel contain non-null values
...
          band_1_saturated:
            bit_index: 0
            value: 0
            description: Band 1 is saturated
```

This information is written into the NetCDF storage units

```
        short pixelquality(time, y, x) ;
                pixelquality:grid_mapping = "crs" ;
                pixelquality:units = "1" ;
                pixelquality:long_name = "Quality Control" ;
                pixelquality:valid_range = 0, 16384 ;
                pixelquality:QA_index = "Bits are listed from the MSB (bit 13) to the LSB (bit 0)
Bit    Value     Description
13      0       Cloud Shadow (Fmask)
12      0       Cloud Shadow (ACCA)
11      0       Cloud (Fmask)
10      0       Cloud (ACCA)
9       1       Land observation
9       0       Sea observation
8       1       All bands for this pixel contain non-null values
7       0       Band 7 is saturated
6       0       Band 6-2 is saturated
5       0       Band 6-1 is saturated
4       0       Band 5 is saturated
3       0       Band 4 is saturated
2       0       Band 3 is saturated
1       0       Band 2 is saturated
0       0       Band 1 is saturated" ;
                pixelquality:flag_masks = 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192 ;
                pixelquality:flag_meanings = "no_band_1_saturated no_band_2_saturated no_band_3_saturated no_band_4_saturated no_band_5_saturated no_band_6_1_saturated no_band_6_2_saturated no_band_7_saturated contiguity land_obs no_cloud_acca no_cloud_fmask no_cloud_shadow_acca no_cloud_shadow_fmask" ;
```
