### ISSUE TITLE
Virtual products using `reproject` return "Key error" if dask_chunks does not include x and y

### ISSUE THREAD

**Issue by robbibt** [opendatacube/datacube-core#888]
### Expected behaviour
I am using the virtual products `construct`  to create a virtual product with custom reprojection/resampling ([YAML here](https://github.com/GeoscienceAustralia/dea-notebooks/blob/rbt/MAHTS/MAHTS_virtual_products.yaml)):

```
reprojected = {'reproject': dict(output_crs=str(crs), 
                                 resolution=[-30, 30]),
               'input': product,
               'resampling': 'average'}

test = construct(**reprojected)
```

This creates a virtual product that looks like this:

```
input:
  input:
    collate:
    - gqa_iterative_mean_xy: &id001
      - 0
      - 1
      group_by: solar_day
      measurements: &id002
      - nbart_blue
      - nbart_green
      - nbart_red
      - nbart_nir
      - nbart_swir_1
      - nbart_swir_2
      - oa_nbart_contiguity
      - oa_fmask
      product: ga_ls5t_ard_3
      resampling: &id003
        '*': average
        oa_fmask: nearest
    - gqa_iterative_mean_xy: *id001
      group_by: solar_day
      measurements: *id002
      product: ga_ls7e_ard_3
      resampling: *id003
    - gqa_iterative_mean_xy: *id001
      group_by: solar_day
      measurements: *id002
      product: ga_ls8c_ard_3
      resampling: *id003
  output:
    blue:
      dtype: float32
      formula: nbart_blue
    contiguity:
      dtype: bool
      formula: oa_nbart_contiguity
    fmask:
      formula: ((oa_fmask == 1) | (oa_fmask == 4) | (oa_fmask == 5))
    green:
      dtype: float32
      formula: nbart_green
    nir:
      dtype: float32
      formula: nbart_nir
    red:
      dtype: float32
      formula: nbart_red
    swir1:
      dtype: float32
      formula: nbart_swir_1
    swir2:
      dtype: float32
      formula: nbart_swir_2
  transform: datacube.virtual.transformations.Expressions
reproject:
  output_crs: epsg:32650
  resolution:
  - -30
  - 30
resampling: average
```

I expect this product to load regardless of what chunking is specified using `dask_chunks`.

### Actual behaviour

If I load this product using `'dask_chunks': {}`, it will fail with a `KeyError: 'y'`:

```
query = {'x': (137.05, 137.12),
         'y': (-33.61, -33.64),
         'time': '2018-01',
         'dask_chunks': {}}

ds = test.load(dc, **query)
```

However, if I specify x and y chunks, it works as expected:

```
query = {'x': (137.05, 137.12),
         'y': (-33.61, -33.64),
         'time': '2018-01',
         'dask_chunks': {'x': 1000, 'y': 1000}}

ds = test.load(dc, **query)
```

### Steps to reproduce the behaviour

Traceback:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-89-ec0f8348b48c> in <module>
      4          'dask_chunks': {}}
      5 
----> 6 ds = test.load(dc, **query)
      7 ds

/g/data/v10/public/modules/dea/20191127/lib/python3.6/site-packages/datacube/virtual/impl.py in load(self, dc, **query)
    304         datasets = self.query(dc, **query)
    305         grouped = self.group(datasets, **query)
--> 306         return self.fetch(grouped, **query)
    307 
    308 

/g/data/v10/public/modules/dea/20191127/lib/python3.6/site-packages/datacube/virtual/impl.py in fetch(self, grouped, **load_settings)
    835                                                                 grouped.box.dims + geobox.dims,
    836                                                                 dask_chunks)
--> 837                                                  for raster in rasters], dim='time')
    838 
    839         result.attrs['crs'] = geobox.crs

/g/data/v10/public/modules/dea/20191127/lib/python3.6/site-packages/datacube/virtual/impl.py in <listcomp>(.0)
    835                                                                 grouped.box.dims + geobox.dims,
    836                                                                 dask_chunks)
--> 837                                                  for raster in rasters], dim='time')
    838 
    839         result.attrs['crs'] = geobox.crs

/g/data/v10/public/modules/dea/20191127/lib/python3.6/site-packages/datacube/virtual/impl.py in reproject_band(band, geobox, resampling, dims, dask_chunks)
    850     dependencies = [band.data]
    851 
--> 852     spatial_chunks = tuple(dask_chunks[k] for k in geobox.dims)
    853     gt = GeoboxTiles(geobox, spatial_chunks)
    854     new_layer = {}

/g/data/v10/public/modules/dea/20191127/lib/python3.6/site-packages/datacube/virtual/impl.py in <genexpr>(.0)
    850     dependencies = [band.data]
    851 
--> 852     spatial_chunks = tuple(dask_chunks[k] for k in geobox.dims)
    853     gt = GeoboxTiles(geobox, spatial_chunks)
    854     new_layer = {}

KeyError: 'y'
```

### Environment information

* Which ``datacube --version`` are you using? `'1.7+142.g7f8581cf'`
* What datacube deployment/enviornment are you running against? NCI, `module load dea/20191127`
