### ISSUE TITLE
Virtual product aggregate dimension bug

### ISSUE THREAD

**Issue by uchchwhash** [opendatacube/datacube-core#916]
### Expected behaviour
This recipe:

```yaml
            aggregate: xarray_reduction
            method: sum
            group_by: year
            input:
                product: ls5_nbart_geomedian_annual
                measurements: [red]
```
should be a no-op.

### Actual behaviour
```
ValueError: coordinate 'time' is a DataArray dimension, but it has shape () rather than expected shape (1,) matching the dimension size
````

This is caused by inconsistent behaviour of `xarray.DataArray.groupby` which drops the time dimension if there is only one dataset in the group.

### Environment information
* Which ``datacube --version`` are you using?
Commit aad9f10c99aa74178d21526e9e7ec051036e3533.
