### ISSUE TITLE
Store Machine Readable Spectral Response Information

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-core#93]
We've been told by the science people that merely storing central and min/max wavelengths is insufficient, and we will need to store full spectral response information for each observation variable.

There doesn't seem to be an existing standard way for specifying this in the CF Conventions, so we will have to come up with our own.

This issue follows on from #88.

_Simon Oliver:_

> Also investigating spectral response function inclusion with the aim to enable band equivalence based on spectral response - centre wavelength, and range of acceptable limits for equivalence. Remote Sensing scientists have differing ideas on what constitutes band equivalence so a range could be used for this. i.e. does target sensor have values in range based on spectral response or min/max?

**Comment by omad** [comment]
Using the Relative Spectral Response data available from http://landsat.usgs.gov/instructions.php, 
a possible example definition in the YAML Storage Configurations for Landsat 5 would be:

``` yaml
measurements:
    'band_10':
        <<: *MEASUREMENT_DEFAULTS
        src_varname: '10'
        wavelength_range: 420, 550   # in nanometers
        relative_spectral_response: 0.0007, 0.0008, 0.0008, 0.0009, 0.0009 ... , 0.0054, 0.0052  # 131 elements in array

        attrs:
            color: Blue
```

**wavelength_range** specifies the min/max wavelength for which the spectral response data is provided
**relative_spectral_response** specifies an array of response values, spread between min/max wavelength
