### ISSUE TITLE
NoneType attribute to_crs with netCDF file

### ISSUE THREAD

**Issue by jankovicgd** [opendatacube/datacube-core#953]
Hey all, I am getting an error when loading netcdf file that was successfully indexed in ODC

### Expected behaviour
Expecting to load the data.

### Actual behaviour

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
 in 
      4     'time': ('1998-02-25', '2020-03-05')
      5 }
----> 6 data = dc.load(product='BMON_UTM', **query)
      7 data

~/miniconda3/envs/test_datacube_netcdf/lib/python3.6/site-packages/datacube/api/core.py in load(self, product, measurements, output_crs, resolution, resampling, skip_broken_datasets, dask_chunks, like, fuse_func, align, datasets, progress_cbk, **query)
    293             legacy_args['use_threads'] = use_threads
    294 
--> 295         observations = datasets or self.find_datasets(product=product, like=like, ensure_location=True, **query)
    296         if not observations:
    297             return xarray.Dataset()

~/miniconda3/envs/test_datacube_netcdf/lib/python3.6/site-packages/datacube/api/core.py in find_datasets(self, **search_terms)
    328         .. seealso:: :meth:`group_datasets` :meth:`load_data` :meth:`find_datasets_lazy`
    329         """
--> 330         return list(self.find_datasets_lazy(**search_terms))
    331 
    332     def find_datasets_lazy(self, limit=None, ensure_location=False, **kwargs):

~/miniconda3/envs/test_datacube_netcdf/lib/python3.6/site-packages/datacube/api/core.py in (.0)
    353 
    354         if ensure_location:
--> 355             datasets = (dataset for dataset in datasets if dataset.uris)
    356 
    357         return datasets

~/miniconda3/envs/test_datacube_netcdf/lib/python3.6/site-packages/datacube/api/core.py in select_datasets_inside_polygon(datasets, polygon)
    709     query_crs = polygon.crs
    710     for dataset in datasets:
--> 711         if intersects(polygon, dataset.extent.to_crs(query_crs)):
    712             yield dataset
    713 

AttributeError: 'NoneType' object has no attribute 'to_crs'
```

### Steps to reproduce the behaviour

```python
import datacube
dc = datacube.Datacube()
query = {
    'lat': (47.8, 48.6),
    'lon': (15.9, 16.7),
    'time': ('1998-02-25', '2020-03-05')
}
data = dc.load(product='BMON_UTM', **query) # also with output_crs
```

Product:
```yml
name: BMON_UTM
description: Bodenfeuchtmonitoring data
metadata_type: eo

storage:
  crs: EPSG:32633
  resolution:
    x: 500
    y: -500

metadata:
  format: { name: NetCDF }
  instrument: { name: Mixed }
  platform: { code: Mixed }
  product_type: BMON_UTM

measurements:
  - name: RZSM
    aliases: []
    units: "percentage"
    dtype: float64
    nodata: -999
  - name: SSM
    aliases: []
    units: "percentage"
    dtype: float64
    nodata: -999

```

Dataset:
```yml
creation_dt: 2019-09-24T00:00:00
extent:
  center_dt: 2016-01-01T00:00:00
  from_dt: 2016-01-01T00:00:00
  to_dt: 2016-01-01T00:00:00
  coord:
    ll:
      lat: 45.76
      lon: 8.47
    lr:
      lat: 45.801
      lon: 17.467
    ul:
      lat: 49.316
      lon: 8.995
    ur:
      lat: 17.74
      lon: 49.39
format:
  name: NetCDF
grid_spatial:
  projection:
    geo_ref_points:
      ll:
        x: -9916.03187
        y: 5074610.56484
      lr:
        x: 699583.962617367
        y: 5074610.569121732
      ul:
        x: -9916.03737916
        y: 5491110.56911839
      ur:
        x: 699583.962617362
        y: 5491110.56911839
      spatial_reference: EPSG:32633
image:
  bands:
    RZSM:
      path: /home/nikola/Data/projects/BMON/v4/BMON_DM_ENSEMBLE_500m_20160101000000_v4_epsg32633.nc
      layer: RZSM
      band: 1
    SSM:
      path: /home/nikola/Data/projects/BMON/v4/BMON_DM_ENSEMBLE_500m_20160101000000_v4_epsg32633.nc
      layer: SSM
      band: 1
instrument:
  name: Mixed
name: BMON_UTM
platform:
  code: Mixed
product_type: BMON_UTM
id: a7272a10-43ca-43d5-87fa-4511cd7389de
```

File: https://drive.google.com/open?id=1WlV15bU2IghVJ2VMLUKAXOt52co4W83K

### Environment information

* Which ``datacube --version`` are you using? 1.7
* What datacube deployment/enviornment are you running against? conda environment
