### ISSUE TITLE
Indexed Sentinel-2 data has different spatial extent

### ISSUE THREAD

**Issue by clausmichele** [opendatacube/datacube-core#971]
I think there is an issue indexing Sentinel-2 data:
the original jp2 file has coverage (via gdalinfo)
```
Upper Left  (  600000.000, 5200020.000) ( 10d18'50.53"E, 46d56'46.21"N)
Lower Left  (  600000.000, 5090220.000) ( 10d17'25.74"E, 45d57'29.75"N)
Upper Right (  709800.000, 5200020.000) ( 11d45'20.11"E, 46d55'13.93"N)
Lower Right (  709800.000, 5090220.000) ( 11d42'22.52"E, 45d56' 0.59"N)
Center      (  654900.000, 5145120.000) ( 11d 0'59.72"E, 46d26'30.73"N)
```
 
but when loaded with ODC is:

```
600005.0
709795.0
5090225.0
5200015.0
```

### Environment information
datacube version: 1.8

What should I check?

EDIT: I wrongly wrote ingesting instead of indexing

**Comment by Kirill888** [comment]
What is a valid data polygon of the given granule?
Also do you really need to do ingestion? What gains are you hoping to achieve with ahead of time reprojection?

**Comment by clausmichele** [comment]
Indexing is what I mean. How do I check the valid data polygon? Opening the original .jp2 in QGIS gives the full original extent.
I attach the yaml file I am using, as you see the extent is different to what I get loading the data. The preparation script I use is the following https://github.com/opendatacube/datacube-dataset-config/blob/master/old-prep-scripts/sen2cor_prepare.py

```
acquisition:
  groundstation:
    code: MPS_
creation_dt: '2018-11-14T14:57:34Z'
extent:
  center_dt: '2018-10-11T10:10:20.457Z'
  coord:
    ll:
      lat: 45.95826451792459
      lon: 10.290484068721138
    lr:
      lat: 45.933496504418194
      lon: 11.706254333033241
    ul:
      lat: 46.946168253505306
      lon: 10.31403528036784
    ur:
      lat: 46.92053638772221
      lon: 11.755584916051989
  from_dt: '2018-10-11T10:10:20.457Z'
  to_dt: '2018-10-11T10:10:20.457Z'
format:
  name: JPEG2000
grid_spatial:
  projection:
    geo_ref_points:
      ll:
        x: 600000
        y: 5090220
      lr:
        x: 709800
        y: 5090220
      ul:
        x: 600000
        y: 5200020
      ur:
        x: 709800
        y: 5200020
    spatial_reference: PROJCS["WGS 84 / UTM zone 32N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS
      84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",9],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32632"]]
id: 90f1a718-93b2-4cf2-b7de-93331092ace1
image:
  bands:
    AOT_10m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R10m/T32TPS_20181011T101019_AOT_10m.jp2
    AOT_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_AOT_20m.jp2
    AOT_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_AOT_60m.jp2
    B01_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_B01_60m.jp2
    B02_10m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R10m/T32TPS_20181011T101019_B02_10m.jp2
    B02_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_B02_20m.jp2
    B02_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_B02_60m.jp2
    B03_10m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R10m/T32TPS_20181011T101019_B03_10m.jp2
    B03_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_B03_20m.jp2
    B03_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_B03_60m.jp2
    B04_10m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R10m/T32TPS_20181011T101019_B04_10m.jp2
    B04_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_B04_20m.jp2
    B04_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_B04_60m.jp2
    B05_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_B05_20m.jp2
    B05_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_B05_60m.jp2
    B06_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_B06_20m.jp2
    B06_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_B06_60m.jp2
    B07_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_B07_20m.jp2
    B07_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_B07_60m.jp2
    B08_10m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R10m/T32TPS_20181011T101019_B08_10m.jp2
    B09_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_B09_60m.jp2
    B11_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_B11_20m.jp2
    B11_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_B11_60m.jp2
    B12_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_B12_20m.jp2
    B12_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_B12_60m.jp2
    B8A_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_B8A_20m.jp2
    B8A_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_B8A_60m.jp2
    SCL_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_SCL_20m.jp2
    SCL_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_SCL_60m.jp2
    WVP_10m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R10m/T32TPS_20181011T101019_WVP_10m.jp2
    WVP_20m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R20m/T32TPS_20181011T101019_WVP_20m.jp2
    WVP_60m:
      layer: 1
      path: /mnt/T32TPS/S2B_MSIL2A_20181011T101019_N0206_R022_T32TPS_20181011T122059.SAFE/GRANULE/L2A_T32TPS_A008342_20181011T101020/IMG_DATA/R60m/T32TPS_20181011T101019_WVP_60m.jp2
instrument:
  name: MSI
lineage:
  source_datasets: {}
platform:
  code: SENTINEL_2A
processing_level: L2Ap
product_type: S2MSI2Ap


```
